---
# This playbook deploys and configures the image builder software on RHEL 7 and RHEL 8
#

- name: Deploying Image Builder
  hosts: all
  gather_facts: true

  vars:
    composer_main_pkg: "osbuild-composer"

  tasks:

  # packages are available in base repos.
  # for completeness, we would check registration and repository configuration
  # but we aren't going to as this system will always be installed by
  # Satellite
    - name: "Ensure repos for RHEL7, for later releases imagebuilder pkgs are in the base repos"
      when: ansible_distribution_major_version == "7"
      block:
        - name: "DEPRECATION WARNING"
          ansible.builtin.debug:
            msg: "RHEL7 has reached end of maintenance - this functionality in no longer supported and will be removed"

        - name: "Configure RHEL7 Repos"
          community.general.rhsm_repository:
            name: rhel-7-server-extras-rpms

        - name: Set the imagebuilder package name
          ansible.builtin.set_fact:
            composer_main_pkg: "lorax-composer"

    - name: "Install imagebuilder packages"
      ansible.builtin.dnf:
        name:
          - "{{ composer_main_pkg }}"
          - composer-cli
          - cockpit
          - cockpit-composer
          - bash-completion
        state: present

    - name: "Enable composer socket"
      ansible.builtin.service:
        name: "{{ composer_main_pkg }}.socket"
        state: started
        enabled: true

    - name: "Enable cockpit socket"
      ansible.builtin.service:
        name: cockpit.socket
        state: started
        enabled: true

    - name: "Configure firewall for services"
      ansible.posix.firewalld:
        service: cockpit
        state: enabled
        immediate: true
        permanent: true
