# This task checks the registration of the local node
# if the node is not registered to the Red Hat CDN, 
# the play determines the OS release and generates the appropriate
# repo configuration for imagebuilder based on the configured system repositories
# See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/composing_a_customized_rhel_system_image/managing-repositories_composing-a-customized-rhel-system-image

- set_fact: 
  cdn_registered: false
  no_log: true

- name: "determine registration"
  command: "subscription-manager config | grep baseurl | grep cdn.redhat.com"
  register: result

- set_fact:
  cdn_registered: true
  when: result.stdout != ""
  no_log: true

- name: "if we are not registered to CDN then we need to configure custom repos"
  block:
  # determine the OS release this is available via ansible_distribution_version when gather_facts is true
  # we set this in deploy_imagebuilder

  - name: "create the /etc configuration directory"
    ansible.builtin.file:
      path: "{{ osbuild_config_dir }}"
      state: "directory"

  - name: "load the repo information for this OS"
    yum_repository_info:
      path: "{{ repo_file }}"

  - name: "template out the new osbuilder source"
    template:
      src: "templates.os.repo"
      dest: "{{ osbuild_config_dir }}/rhel-{{ ansible_distribution_version | replace('.','') }}.json"

  # create a soft link to the satellite pem
  # restart all the services
  when: cdn_registered == false
