---

# handler to restart the osbuild-composer service

- name: "Restart osbuild-composer"
  block:

    - name: "Stop all osbuild services"
      ansible.builtin.systemd_service:
        name: "osbuild\\*"
        state: stopped

    - name: "Reset failed state on all osbuild services"
      ansible.builtin.command: "systemctl reset-failed osbuild\\*"
      changed_when: true

    - name: "Restart the osbuild socket"
      ansible.builtin.systemd_service:
        name: "osbuild-composer.socket"
        state: started
